version: '3'

services:
  neo4j:
    image: neo4j:5.17.0
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/demo1234
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/conf
      - ./plugins:/plugins
      - ./import:/import
      - ./reports:/reports
      - ./examples:/examples
